### ISSUE TITLE
Launch MVP site

### ISSUE THREAD

**Issue by rooneywp** [18F/join.tts.gsa.gov#8]
**Launch the MVP version of our TTS join site.**
- A way for people to know what TTS is
- A way for people to know that there are different parts of TTS
- A way for people to apply for TTS jobs
- A way for people to what the hiring process is

**To-Do**

- [x] Register Domain
- [x] Get on Federalist
- [x] Create/Transfer initial site copy
- [x] Create job posting template
- [x] Copy Editing (Writing Lab)
- [x] Create first live job posting
- [x] QA site
- [x] Confirm new process with Outreach

**Comment by JennMoran** [comment]
Tasks completed and site launched.
